# Generated by Django 5.2.12 on 2026-03-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0005_visitorlog_status_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="maximum_uses",
            field=models.PositiveSmallIntegerField(
                default=0,
                db_default=0,
                help_text="Maximum number of uses. Use zero for unlimited number of uses.",
            ),
        ),
    ]
