name: Python / Django

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv: [fmt,lint,mypy]
    env:
      TOXENV: ${{ matrix.toxenv }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install and run tox
        run: |
          pip install tox
          tox

  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: "3.10"
            toxenv: py310-django52
          - python: "3.11"
            toxenv: py311-django52
          - python: "3.12"
            toxenv: py312-django52
          - python: "3.13"
            toxenv: py313-django52

    env:
      TOXENV: ${{ matrix.toxenv }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install and run tox
        run: |
          pip install tox
          tox
